import pygame

BG_COLOR = (255,255,255)
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

#player settings
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
PLAYER_SPEED = 3.5
PLAYER_IMAGE_PATH = "obrazky/spaceship.png"
PLAYER_BULLET_IMAGE_PATH = "obrazky/bullet.png"
PLAYER_BULLET_SPEED = 5


#enemy settings
ENEMY_DROP_SPEED = 10
ENEMY_SPEED = 2
ENEMY_SCALE= 0.76
BOSS_SCALE = 3
ENEMY_IMAGE_PATH = "obrazky/alien{}.png"
ENEMY_BULLET_IMAGE_PATH = "obrazky/alien_bullet.png"
ENEMY_BULLET_SPEED = 4